# === .github/workflows/ci_cd.yml ===
name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - qa
      - prod
  pull_request:
    branches:
      - dev
      - qa
      - prod

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Ruff Linter
        run: ruff check .

      - name: Run Pytest
        run: pytest

  deploy:
    needs: lint-and-test
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Deployment Step
        run: 'echo "Deploying to environment: ${{ github.ref_name }} (simulated)"'
